version: '3'

services:
  eshop.catalog:
    image: eshop.catalog
    build:
      context: ./eShop.Catalog
      dockerfile: Dockerfile
    #depends_on:
      #- sql.data
      #- rabbitmq

  #sql.data:
  #  image: microsoft/mssql-server-linux:2017-latest

  #rabbitmq:
  #  image: rabbitmq:3-management
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"